# Generated by Django 3.0.1 on 2022-10-09 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20221009_1132'),
    ]

    operations = [
        migrations.RenameField(
            model_name='departments',
            old_name='dep_decription',
            new_name='dep_description',
        ),
    ]
